name: balloon_game

description: "balloon_game"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  audioplayers: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/2026_012_0-82.mp3 # game bgm
    - assets/2026_003_0-80.mp3 # home bgm

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon_001.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon_001.png"
  remove_alpha_ios: true